---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openstack-cinder-csi
  namespace: os-tenant
spec:
  kubeConfig:
    secretRef:
      name: os-tenant-cluster-kubeconfig
  targetNamespace: kube-system
  storageNamespace: kube-system
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: openstack-cinder-csi
      version: 2.33.1
      sourceRef:
        kind: HelmRepository
        name: openstack-cinder-csi
      interval: 5m
  releaseName: openstack-cinder-csi
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
  values:
    csi:
      provisioner:
        extraArgs: |
          - --strict-topology
      snapshotter:
        extraRbac:
          - apiGroups:
              - ''
            resources:
              - secrets
            verbs:
              - get
              - list
      resizer:
        extraRbac:
          - apiGroups:
              - ''
            resources:
              - secrets
            verbs:
              - get
              - list
              - watch
      plugin:
        nodePlugin:
          nodeSelector:
            topology.kubernetes.io/region: ru-3
          extraArgs: |-
            - --additional-topology
            - topology.kubernetes.io/region=ru-3
          # controllerPlugin:
          # extraArgs: |-
          #   - "--pvc-annotations"
    secret:
      enabled: true
      hostMount: false
      create: false
      name: cloud-config
      filename: cloud.conf
    storageClass:
      enabled: false
      custom: |-
        ---
        apiVersion: storage.k8s.io/v1
        kind: StorageClass
        metadata:
          name: fast.ru-3
        provisioner: cinder.csi.openstack.org
        reclaimPolicy: Delete
        volumeBindingMode: WaitForFirstConsumer
        allowVolumeExpansion: true
        parameters:
          region: ru-3
          type: fast.ru-3
        allowedTopologies:
          - matchLabelExpressions:
              - key: topology.cinder.csi.openstack.org/zone
                values:
                  - ru-3b
                  - ru-3c
