---
# Подготовленные обазы k8s взяты из https://github.com/osism/k8s-capi-images
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Image
metadata:
  name: kube-1.32.2
  namespace: os-tenant
spec:
  managedOptions:
    onDelete: detach
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  resource:
    name: kube-v1.32.2
    content:
      diskFormat: qcow2
      download:
        url: https://swift.services.a.regiocloud.tech/swift/v1/AUTH_b182637428444b9aa302bb8d5a5a418c/openstack-k8s-capi-images/ubuntu-2204-kube-v1.32/ubuntu-2204-kube-v1.32.2.qcow2
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Image
metadata:
  name: kube-1.32.8
  namespace: os-tenant
spec:
  managedOptions:
    onDelete: detach
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  resource:
    name: kube-v1.32.8
    content:
      diskFormat: qcow2
      download:
        url: https://swift.services.a.regiocloud.tech/swift/v1/AUTH_b182637428444b9aa302bb8d5a5a418c/openstack-k8s-capi-images/ubuntu-2204-kube-v1.32/ubuntu-2204-kube-v1.32.8.qcow2
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Image
metadata:
  name: kube-1.33
  namespace: os-tenant
spec:
  managedOptions:
    onDelete: detach
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  resource:
    name: kube-v1.33
    content:
      diskFormat: qcow2
      download:
        url: https://swift.services.a.regiocloud.tech/swift/v1/AUTH_b182637428444b9aa302bb8d5a5a418c/openstack-k8s-capi-images/ubuntu-2404-kube-v1.33/ubuntu-2404-kube-v1.33.qcow2
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Image
metadata:
  name: kube-1.34.0
  namespace: os-tenant
spec:
  managedOptions:
    onDelete: detach
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  resource:
    name: kube-v1.34.0
    content:
      diskFormat: qcow2
      download:
        url: https://swift.services.a.regiocloud.tech/swift/v1/AUTH_b182637428444b9aa302bb8d5a5a418c/openstack-k8s-capi-images/ubuntu-2404-kube-v1.34/ubuntu-2404-kube-v1.34.qcow2
