---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: cloud-provider-openstack
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: os-tenant-cluster
  strategy: Reconcile
  resources:
    - name: cloud-config
      kind: Secret
