---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: docker-tenant-default-worker-bootstraptemplate
  namespace: docker-tenant
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration: {}
