---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: occm
  namespace: occm
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: openstack-cloud-controller-manager
      version: 2.33.1
      sourceRef:
        kind: HelmRepository
        name: cloud-provider-openstack
      interval: 5m
  releaseName: openstack-cloud-controller-manager
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
  values:
    nodeSelector:
      node-role.kubernetes.io/control-plane: ''
    tolerations:
      - key: node.cloudprovider.kubernetes.io/uninitialized
        value: 'true'
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
    controllerExtraArgs: |-
      - --use-service-account-credentials=false
    secret:
      create: false
      name: cloudconf
    logVerbosityLevel: 2
