---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cluster-api-operator
  namespace: default
spec:
  interval: 5m
  url: https://kubernetes-sigs.github.io/cluster-api-operator
